spring:
  application:
    name: MSLaboratoir
  cloud:
    config:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8888"
management:
  endpoints:
    web:
      exposure:
        include: health,refresh
