spring.application.name=MSPatientMedcin
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888
management.endpoints.web.exposure.include=refresh,health

spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true

#jdbc url : jdbc:h2:file:./Database/Data/ClinicPatientMedcin
