spring.application.name=demoApiGateway
server.port=8085


#eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Use JVM DNS resolver so Netty can resolve Windows hostnames like tim-inter.mshome.net
spring.cloud.gateway.httpclient.wiretap=false
reactor.netty.http.client.useNettyResolver=false

# CORS Configuration for the API Gateway
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

